# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d970106fc2e6e0f661d310f10c547c270616800a8eda6dc133cf0a68dfd50169e2d39c12f81c9f41815695275ca3c47648da094302edbb363d897d62327772d

test:
  secret_key_base: d1c20853ae586d5e2ceb6e35ed1111dc599ed9b3d212b56d5906f50cefefb7bbd428bf896d8c46f2baa5c7b3d148deeb3711ae76f77b4f897e1bfdd543eeeb09

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
